import { Brief, BriefItem, TRUST_COLOR } from "./types";

// Mirrors engine/lib/render_html.py: a self-contained, dark, no-JS HTML brief
// you can drop into Slack/Notion/email. Generated client-side from the brief
// already on screen, so export is instant and matches the displayed results.

const CSS = `
:root{--bg:#0f1117;--surface:#1a1d27;--border:#2d3148;--text:#e8e9f0;--muted:#8a8fa8;--accent:#7c6cfc}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,sans-serif;line-height:1.5}
.wrap{max-width:760px;margin:0 auto;padding:32px 20px 64px}
h1{margin:0 0 4px;font-size:26px}
.meta{color:var(--muted);font-size:13px;margin-bottom:20px}
.warn{background:#3a1d1d;border:1px solid #f85149;color:#ffb4ad;padding:10px 14px;border-radius:8px;margin:10px 0;font-size:14px}
.item{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:14px 16px;margin:12px 0}
.item h3{margin:0 0 6px;font-size:16px}
.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;font-size:12px;color:var(--muted);margin-bottom:8px}
.tag{background:#262a38;border-radius:5px;padding:2px 7px;font-family:'JetBrains Mono',ui-monospace,monospace}
.quote{color:var(--text);border-left:2px solid var(--border);padding-left:12px;margin:8px 0;font-size:14px}
.flags{color:#d29922;font-size:12px}
.trustbar{height:6px;border-radius:3px;background:#262a38;overflow:hidden;margin:8px 0 2px}
.trustfill{height:100%}
a{color:var(--accent)}
footer{color:var(--muted);font-size:12px;margin-top:28px;border-top:1px solid var(--border);padding-top:14px}`;

function esc(s: string): string {
  return (s || "").replace(/[&<>"]/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] as string,
  );
}

function itemHtml(item: BriefItem, i: number): string {
  const color = TRUST_COLOR[item.trust_label];
  const pct = Math.round(item.trust * 100);
  const head = item.title || item.text.slice(0, 70);
  const rating = item.rating != null ? `<span class=tag>${item.rating}★</span>` : "";
  const date = item.published_at ? new Date(item.published_at).toLocaleDateString() : "";
  const quote = item.text && item.text !== head ? `<div class=quote>${esc(item.text.slice(0, 400))}</div>` : "";
  const flags = item.flags.length
    ? `<div class=flags>flags: ${item.flags.map((f) => esc(f.name)).join(", ")}</div>`
    : "";
  const link = item.url ? `<div><a href="${esc(item.url)}">${esc(item.source)} link →</a></div>` : "";
  return `<div class=item><h3>${i}. ${esc(head)}</h3>
<div class=row><span class=tag>${esc(item.source)}</span>${rating}<span>${date}</span>
<span style="color:${color}">● ${item.trust_label} ${item.trust.toFixed(2)}</span></div>
<div class=trustbar><div class=trustfill style="width:${pct}%;background:${color}"></div></div>
${quote}${flags}${link}</div>`;
}

export function briefToHtml(brief: Brief): string {
  const warnings = brief.warnings.map((w) => `<div class=warn>⚠️ ${esc(w)}</div>`).join("");
  const items = brief.items.map((it, i) => itemHtml(it, i + 1)).join("");
  return `<!doctype html><html lang=en><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>Winnow: ${esc(brief.topic)}</title><style>${CSS}</style></head><body><div class=wrap>
<h1>Winnow: ${esc(brief.topic)}</h1>
<div class=meta>synced ${new Date(brief.generated_at).toLocaleDateString()} · ${brief.item_count} items · ranked by authenticity, not raw engagement</div>
${warnings}${items}
<footer>Generated by Winnow · re-run: <code>winnow "${esc(brief.topic)}"</code></footer>
</div></body></html>`;
}

export function downloadBrief(brief: Brief): void {
  const blob = new Blob([briefToHtml(brief)], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${brief.topic.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-brief.html`;
  a.click();
  URL.revokeObjectURL(url);
}
