"""Render a Brief to a self-contained, shareable HTML page.

No JS, no external CSS, inline everything - works offline, drops into Slack/
Notion/email. Dark by default. The authenticity score is the visual hero:
a colored trust bar per item, the thing last30days has no concept of.
"""

from __future__ import annotations

import html

from .schema import Brief

_TRUST_COLOR = {"trusted": "#3fb950", "mixed": "#d29922", "suspicious": "#f85149"}

_CSS = """
:root{--bg:#0f1117;--surface:#1a1d27;--border:#2d3148;--text:#e8e9f0;--muted:#8a8fa8;--accent:#7c6cfc}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,sans-serif;line-height:1.5}
.wrap{max-width:760px;margin:0 auto;padding:32px 20px 64px}
header h1{margin:0 0 4px;font-size:26px}
.meta{color:var(--muted);font-size:13px;margin-bottom:20px}
.warn{background:#3a1d1d;border:1px solid #f85149;color:#ffb4ad;padding:10px 14px;border-radius:8px;margin:10px 0;font-size:14px}
.item{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:14px 16px;margin:12px 0}
.item h3{margin:0 0 6px;font-size:16px}
.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;font-size:12px;color:var(--muted);margin-bottom:8px}
.tag{background:#262a38;border-radius:5px;padding:2px 7px;font-family:'JetBrains Mono',ui-monospace,monospace}
.quote{color:var(--text);border-left:2px solid var(--border);padding-left:12px;margin:8px 0;font-size:14px}
.flags{color:#d29922;font-size:12px}
.trustbar{height:6px;border-radius:3px;background:#262a38;overflow:hidden;margin:8px 0 2px}
.trustfill{height:100%}
a{color:var(--accent)}
footer{color:var(--muted);font-size:12px;margin-top:28px;border-top:1px solid var(--border);padding-top:14px}
"""


def to_html(brief: Brief) -> str:
    def esc(s: str) -> str:
        return html.escape(s or "")

    parts: list[str] = []
    parts.append("<!doctype html><html lang=en><head><meta charset=utf-8>")
    parts.append('<meta name=viewport content="width=device-width,initial-scale=1">')
    parts.append(f"<title>Winnow: {esc(brief.topic)}</title><style>{_CSS}</style></head><body><div class=wrap>")
    parts.append(f"<header><h1>Winnow: {esc(brief.topic)}</h1>")
    parts.append(f'<div class=meta>synced {brief.generated_at:%Y-%m-%d} · {len(brief.items)} items · ranked by authenticity, not raw engagement</div></header>')

    for w in brief.warnings:
        parts.append(f"<div class=warn>⚠️ {esc(w)}</div>")

    for i, item in enumerate(brief.items, 1):
        color = _TRUST_COLOR.get(item.authenticity.label, "#8a8fa8")
        pct = int(item.authenticity.score * 100)
        head = item.title or (item.text[:70] + "…" if len(item.text) > 70 else item.text)
        rating = f"<span class=tag>{item.rating:.0f}★</span>" if item.rating else ""
        date = f"{item.published_at:%Y-%m-%d}" if item.published_at else ""
        parts.append("<div class=item>")
        parts.append(f"<h3>{i}. {esc(head)}</h3>")
        parts.append(f'<div class=row><span class=tag>{esc(item.source)}</span>{rating}'
                     f'<span>{date}</span><span style="color:{color}">● {item.authenticity.label} '
                     f'{item.authenticity.score:.2f}</span></div>')
        parts.append(f'<div class=trustbar><div class=trustfill style="width:{pct}%;background:{color}"></div></div>')
        if item.text and item.text != head:
            parts.append(f"<div class=quote>{esc(item.text[:400])}</div>")
        if item.authenticity.signals:
            flags = ", ".join(esc(s.name) for s in item.authenticity.signals)
            parts.append(f"<div class=flags>flags: {flags}</div>")
        if item.url:
            parts.append(f'<div><a href="{esc(item.url)}">{esc(item.source)} link →</a></div>')
        parts.append("</div>")

    parts.append(f'<footer>Generated by Winnow · re-run: <code>winnow "{esc(brief.topic)}"</code></footer>')
    parts.append("</div></body></html>")
    return "".join(parts)
